apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: example-sso-realm
  labels:
    app: sso
spec:
  realm:
    id: 'myRealm'
    realm: 'myRealm'
    enabled: True
    displayName: 'My Realm'
    displayNameHtml: '<h1 style="font-size: 30px; color: #5e9ca0;">My Realm</h1>'
  instanceSelector:
    matchLabels:
      app: sso