apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: pam-user-developer
spec:
  user:
    username: "user-developer"
    enabled: True
    credentials:
      - type: "password"
        value: "user"
    realmRoles:
      - "developer"
    clientRoles:
      realm-management:
        - "view-realm"
        - "query-users"
        - "view-users"
  realmSelector:
    matchLabels:
      app: sso