apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: pam-ks-client
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: ks-client
    secret: ks-client-secret
    redirectUris: 
      - 'https://<KIE_SERVER_DOMAIN>/*'
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    defaultClientScopes:
      - web-origins
      - profile
      - roles
      - email