apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: pam-bc-client
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
  client:
    clientId: bc-client
    secret: bc-client-secret
    redirectUris: 
      - 'https://<BUSINESS_CENTRAL_DOMAIN>/*'
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    defaultClientScopes:
      - web-origins
      - profile
      - roles
      - email