apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: pam-user-process-admin
spec:
  user:
    username: "user-process-admin"
    enabled: True
    credentials:
      - type: "password"
        value: "user"
    realmRoles:
      - "Administrators"
      - "process-admin"
      - "rest-all"
      - "kie-server"
  realmSelector:
    matchLabels:
      app: sso